#!/bin/sh

# nvim --headless -u tests/init.lua -c "PlenaryBustedDirectory tests/core/lazyflex_spec.lua {minimal_init = 'tests//init.lua', sequential = true}"
nvim --headless -u tests/init.lua -c "PlenaryBustedDirectory tests {minimal_init = 'tests//init.lua', sequential = true}"
